[package]
name = "jamstream-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "jamstream"
path = "src/main.rs"

[dependencies]
jamstream-protocol.workspace = true
jamstream-cloud.workspace = true
