# Generated by scripts/render-packaging.sh from the v0.1.1-beta release; do not edit by hand.
#
# Install: brew install --cask sean-reid/jamstream/jamstream
cask "jamstream" do
  version "0.1.1-beta"
  sha256 "a7672decf5b61946f27c40afcd537ade9af6235e7b990c9b7832ad38d228221a"

  url "https://github.com/sean-reid/jamstream/releases/download/v#{version}/jamstream-app-macos.dmg",
      verified: "github.com/sean-reid/jamstream/"
  name "JamStream"
  desc "Host a short-lived jam server in your own cloud account and play together"
  homepage "https://sean-reid.github.io/jamstream"

  livecheck do
    url :url
    strategy :github_latest
  end

  # The app has no updater of its own: brew upgrade is the update path.
  auto_updates false
  # Info.plist sets LSMinimumSystemVersion 11.0.
  depends_on macos: ">= :big_sur"

  app "JamStream.app"

  # The app writes provider state and session records under
  # ~/Library/Application Support/jamstream (dirs::data_local_dir).
  zap trash: [
    "~/Library/Application Support/jamstream",
    "~/Library/Saved Application State/com.seanreid.jamstream.savedState",
  ]

  # Cloud credentials live in the login keychain (service "jamstream",
  # accounts like "digitalocean.token"), which a cask cannot delete. To
  # remove them by hand after zapping:
  #   security delete-generic-password -s jamstream
  # once per stored account, until it reports no matching item.
end
