[package]
name = "jamstream-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
jamstream-protocol.workspace = true
opus.workspace = true
rubato.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
