# Generated by scripts/render-packaging.sh from the v0.1.6 release; do not edit by hand.
#
# Install: brew install sean-reid/jamstream/jamstream-cli
#
# Prebuilt release binaries, so there is no bottle block and none is
# needed: "building from source" here is extracting one tarball, which is
# why brew on Linux works from the same gnu tarball the downloads page
# serves. That tarball is built on ubuntu-latest, so it needs that glibc or
# newer; older distributions should use cargo install --path crates/cli.
class JamstreamCli < Formula
  desc "Terminal client for jam sessions hosted in your own cloud account"
  homepage "https://sean-reid.github.io/jamstream"
  version "0.1.6"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    # One universal binary for Apple silicon and Intel.
    url "https://github.com/sean-reid/jamstream/releases/download/v0.1.6/jamstream-cli-macos-universal.tar.gz"
    sha256 "894890ff61b02e19583590d18e551469a89fd4191d2af1c9168cca2a418fa4ca"
  end

  on_linux do
    on_intel do
      url "https://github.com/sean-reid/jamstream/releases/download/v0.1.6/jamstream-cli-linux-x86_64.tar.gz"
      sha256 "a83085a68348986eb3bcf8d68df0f0f4aef13b186064304eebcbc9a140b77acc"
    end
    # No arm64 Linux build is published yet; brew falls back to an error
    # rather than installing the wrong architecture.
  end

  livecheck do
    url "https://github.com/sean-reid/jamstream/releases/latest"
    strategy :github_latest
  end

  def install
    bin.install "jamstream"
    generate_completions_from_executable(bin/"jamstream", "completions")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jamstream --version")
    assert_match "host", shell_output("#{bin}/jamstream --help")
  end
end
