# Generated by scripts/render-packaging.sh from the v0.1.1-beta release; do not edit by hand.
#
# Install: brew install sean-reid/jamstream/jamstream-cli
#
# Prebuilt release binaries, so there is no bottle block and none is
# needed: "building from source" here is extracting one tarball, which is
# why brew on Linux works from the same gnu tarball the downloads page
# serves. That tarball is built on ubuntu-latest, so it needs that glibc or
# newer; older distributions should use cargo install --path crates/cli.
class JamstreamCli < Formula
  desc "Terminal client for jam sessions hosted in your own cloud account"
  homepage "https://sean-reid.github.io/jamstream"
  version "0.1.1-beta"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    # One universal binary for Apple silicon and Intel.
    url "https://github.com/sean-reid/jamstream/releases/download/v0.1.1-beta/jamstream-cli-macos-universal.tar.gz"
    sha256 "05e2914197e4591ad874632be8db546a829d80fe2aaa28ae61a1a891d37fe9bb"
  end

  on_linux do
    on_intel do
      url "https://github.com/sean-reid/jamstream/releases/download/v0.1.1-beta/jamstream-cli-linux-x86_64.tar.gz"
      sha256 "a4c57cea53dbcc6545b103dd615e8c7fe11e3ce9e61a347128d65912c804109d"
    end
    # No arm64 Linux build is published yet; brew falls back to an error
    # rather than installing the wrong architecture.
  end

  livecheck do
    url "https://github.com/sean-reid/jamstream/releases/latest"
    strategy :github_latest
  end

  def install
    bin.install "jamstream"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jamstream --version")
    assert_match "host", shell_output("#{bin}/jamstream --help")
  end
end
