[package]
name = "jamstream-broadcast"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
tiny-skia.workspace = true
ab_glyph.workspace = true
image.workspace = true
thiserror.workspace = true
